version: '3'

services:
  db:
    image: postgres
    container_name: 'pg-database'
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    container_name: 'pg-painel'
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9090:8080
