version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./db-volume/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432

  adminer:
    container_name: 'pg-painel'
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9090:8080

  node:
    image: node:12-alpine
    container_name: node_container
    restart: always
    command: sh -c "npm install && npm run dev:server"
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
